# Generated by Django 3.2.22 on 2023-10-12 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genecount',
            name='COG',
        ),
        migrations.RemoveField(
            model_name='genecount',
            name='COG_category',
        ),
        migrations.RemoveField(
            model_name='genecount',
            name='KEGG_KO',
        ),
        migrations.RemoveField(
            model_name='genecount',
            name='KEGG_module',
        ),
        migrations.RemoveField(
            model_name='genedata',
            name='COG_category',
        ),
    ]
