# Generated by Django 3.2.22 on 2023-10-16 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20231012_0956'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeneCount',
        ),
    ]
