# Generated by Django 3.2.22 on 2023-10-17 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_delete_genecount'),
    ]

    operations = [
        migrations.AddField(
            model_name='genedata',
            name='RNAcount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='genedata',
            name='Ribocount',
            field=models.IntegerField(default=0),
        ),
    ]
