# Generated by Django 3.2.22 on 2023-11-01 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20231017_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='genedata',
            name='MAG',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='magdata',
            name='DNAcount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='magdata',
            name='RNAcount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='magdata',
            name='Ribocount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='magdata',
            name='fasta',
            field=models.FilePathField(blank=True, match='*.fa', path='/media/fasta'),
        ),
        migrations.AddField(
            model_name='magdata',
            name='sample',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
