# Generated by Django 3.2.22 on 2023-10-16 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SOP_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(default='en', max_length=5)),
                ('SOP', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=80)),
            ],
        ),
    ]
