# Generated by Django 3.2.22 on 2023-10-18 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SOP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sop_list',
            name='md_path',
            field=models.URLField(default=''),
        ),
    ]
