# Generated by Django 3.2.22 on 2023-10-19 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SOP', '0002_sop_list_md_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sop_list',
            name='category',
        ),
    ]
